#!/bin/bash
set -e

if [ ! -f /etc/kubernetes/admin.conf ]; then
  echo "controller-1 not initialized"
  exit 1
fi

export KUBECONFIG=/etc/kubernetes/admin.conf
CERT_KEY=$(kubeadm init phase upload-certs --upload-certs 2>&1 | grep -A1 'certificate key' | tail -1 | xargs)
kubeadm token create --print-join-command | sed 's/$/ --control-plane --certificate-key '"$CERT_KEY"'/' > /srv/k8s/join-controller

echo "controller token updated"
