class _MemoryInfo:
    rss: int


class Process:
    def __init__(self, pid: int) -> None: ...
    @property
    def pid(self) -> int: ...
    def memory_info(self) -> _MemoryInfo: ...
    def children(self, recursive: bool = False) -> list[Process]: ...


class NoSuchProcess(Exception): ...
