EVENT_CLOSE: int
EVENT_SUBPROCESS_QUIT: int
EVENT_LAUNCH_DONE: int
EVENT_PROGRESS: int
EVENT_APPLIANCE: int
EVENT_LIBRARY: int
EVENT_TRACE: int
EVENT_ENTER: int
EVENT_LIBVIRT_AUTH: int
EVENT_WARNING: int
EVENT_ALL: int

def event_to_string(events): ...

class ClosedHandle(ValueError): ...

class GuestFS:
    def __init__(self, python_return_dict: bool = False, environment: bool = True, close_on_exit: bool = True) -> None: ...
    def __del__(self) -> None: ...
    def close(self) -> None: ...
    def set_event_callback(self, cb, event_bitmask): ...
    def delete_event_callback(self, event_handle) -> None: ...
    def acl_delete_def_file(self, dir: str) -> None: ...
    def acl_get_file(self, path: str, acltype: str) -> str: ...
    def acl_set_file(self, path: str, acltype: str, acl: str) -> None: ...
    def add_cdrom(self, filename: str) -> None: ...
    def add_domain(self, dom: str, libvirturi: str | None = None, readonly: bool | None = None, iface: str | None = None, live: bool | None = None, allowuuid: bool | None = None, readonlydisk: str | None = None, cachemode: str | None = None, discard: str | None = None, copyonread: bool | None = None) -> int: ...
    def add_drive(self, filename: str, readonly: bool | None = None, format: str | None = None, iface: str | None = None, name: str | None = None, label: str | None = None, protocol: str | None = None, server: list[str] | None = None, username: str | None = None, secret: str | None = None, cachemode: str | None = None, discard: str | None = None, copyonread: bool | None = None, blocksize: int | None = None) -> None: ...
    add_drive_opts = add_drive
    def add_drive_ro(self, filename: str) -> None: ...
    def add_drive_ro_with_if(self, filename: str, iface: str) -> None: ...
    def add_drive_scratch(self, size: int, name: str | None = None, label: str | None = None, blocksize: int | None = None) -> None: ...
    def add_drive_with_if(self, filename: str, iface: str) -> None: ...
    def add_libvirt_dom(self, dom, readonly: bool | None = None, iface: str | None = None, live: bool | None = None, readonlydisk: str | None = None, cachemode: str | None = None, discard: str | None = None, copyonread: bool | None = None) -> int: ...
    def aug_clear(self, augpath: str) -> None: ...
    def aug_close(self) -> None: ...
    def aug_defnode(self, name: str, expr: str, val: str) -> dict: ...
    def aug_defvar(self, name: str, expr: str | None) -> int: ...
    def aug_get(self, augpath: str) -> str: ...
    def aug_init(self, root: str, flags: int) -> None: ...
    def aug_insert(self, augpath: str, label: str, before: bool) -> None: ...
    def aug_label(self, augpath: str) -> str: ...
    def aug_load(self) -> None: ...
    def aug_ls(self, augpath: str) -> list[str]: ...
    def aug_match(self, augpath: str) -> list[str]: ...
    def aug_mv(self, src: str, dest: str) -> None: ...
    def aug_rm(self, augpath: str) -> int: ...
    def aug_save(self) -> None: ...
    def aug_set(self, augpath: str, val: str) -> None: ...
    def aug_setm(self, base: str, sub: str | None, val: str) -> int: ...
    def aug_transform(self, lens: str, file: str, remove: bool | None = None) -> None: ...
    def available(self, groups: list[str]) -> None: ...
    def available_all_groups(self) -> list[str]: ...
    def base64_in(self, base64file: str, filename: str) -> None: ...
    def base64_out(self, filename: str, base64file: str) -> None: ...
    def blkdiscard(self, device: str) -> None: ...
    def blkdiscardzeroes(self, device: str) -> bool: ...
    def blkid(self, device: str) -> list[tuple[str, str]] | dict: ...
    def blockdev_flushbufs(self, device: str) -> None: ...
    def blockdev_getbsz(self, device: str) -> int: ...
    def blockdev_getro(self, device: str) -> bool: ...
    def blockdev_getsize64(self, device: str) -> int: ...
    def blockdev_getss(self, device: str) -> int: ...
    def blockdev_getsz(self, device: str) -> int: ...
    def blockdev_rereadpt(self, device: str) -> None: ...
    def blockdev_setbsz(self, device: str, blocksize: int) -> None: ...
    def blockdev_setra(self, device: str, sectors: int) -> None: ...
    def blockdev_setro(self, device: str) -> None: ...
    def blockdev_setrw(self, device: str) -> None: ...
    def btrfs_balance_cancel(self, path: str) -> None: ...
    def btrfs_balance_pause(self, path: str) -> None: ...
    def btrfs_balance_resume(self, path: str) -> None: ...
    def btrfs_balance_status(self, path: str) -> dict: ...
    def btrfs_device_add(self, devices: list[str], fs: str) -> None: ...
    def btrfs_device_delete(self, devices: list[str], fs: str) -> None: ...
    def btrfs_filesystem_balance(self, fs: str) -> None: ...
    def btrfs_filesystem_defragment(self, path: str, flush: bool | None = None, compress: str | None = None) -> None: ...
    def btrfs_filesystem_resize(self, mountpoint: str, size: int | None = None) -> None: ...
    def btrfs_filesystem_show(self, device: str) -> list[str]: ...
    def btrfs_filesystem_sync(self, fs: str) -> None: ...
    def btrfs_fsck(self, device: str, superblock: int | None = None, repair: bool | None = None) -> None: ...
    def btrfs_image(self, source: list[str], image: str, compresslevel: int | None = None) -> None: ...
    def btrfs_qgroup_assign(self, src: str, dst: str, path: str) -> None: ...
    def btrfs_qgroup_create(self, qgroupid: str, subvolume: str) -> None: ...
    def btrfs_qgroup_destroy(self, qgroupid: str, subvolume: str) -> None: ...
    def btrfs_qgroup_limit(self, subvolume: str, size: int) -> None: ...
    def btrfs_qgroup_remove(self, src: str, dst: str, path: str) -> None: ...
    def btrfs_qgroup_show(self, path: str) -> list[dict]: ...
    def btrfs_quota_enable(self, fs: str, enable: bool) -> None: ...
    def btrfs_quota_rescan(self, fs: str) -> None: ...
    def btrfs_replace(self, srcdev: str, targetdev: str, mntpoint: str) -> None: ...
    def btrfs_rescue_chunk_recover(self, device: str) -> None: ...
    def btrfs_rescue_super_recover(self, device: str) -> None: ...
    def btrfs_scrub_cancel(self, path: str) -> None: ...
    def btrfs_scrub_full(self, path: str, readonly: bool | None = None) -> None: ...
    def btrfs_scrub_resume(self, path: str) -> None: ...
    def btrfs_scrub_start(self, path: str) -> None: ...
    def btrfs_scrub_status(self, path: str) -> dict: ...
    def btrfs_set_seeding(self, device: str, seeding: bool) -> None: ...
    def btrfs_subvolume_create(self, dest: str, qgroupid: str | None = None) -> None: ...
    btrfs_subvolume_create_opts = btrfs_subvolume_create
    def btrfs_subvolume_delete(self, subvolume: str) -> None: ...
    def btrfs_subvolume_get_default(self, fs: str) -> int: ...
    def btrfs_subvolume_list(self, fs: str) -> list[dict]: ...
    def btrfs_subvolume_set_default(self, id: int, fs: str) -> None: ...
    def btrfs_subvolume_show(self, subvolume: str) -> list[tuple[str, str]] | dict: ...
    def btrfs_subvolume_snapshot(self, source: str, dest: str, ro: bool | None = None, qgroupid: str | None = None) -> None: ...
    btrfs_subvolume_snapshot_opts = btrfs_subvolume_snapshot
    def btrfstune_enable_extended_inode_refs(self, device: str) -> None: ...
    def btrfstune_enable_skinny_metadata_extent_refs(self, device: str) -> None: ...
    def btrfstune_seeding(self, device: str, seeding: bool) -> None: ...
    def c_pointer(self) -> int: ...
    def canonical_device_name(self, device: str) -> str: ...
    def cap_get_file(self, path: str) -> str: ...
    def cap_set_file(self, path: str, cap: str) -> None: ...
    def case_sensitive_path(self, path: str) -> str: ...
    def cat(self, path: str) -> str: ...
    def checksum(self, csumtype: str, path: str) -> str: ...
    def checksum_device(self, csumtype: str, device: str) -> str: ...
    def checksums_out(self, csumtype: str, directory: str, sumsfile: str) -> None: ...
    def chmod(self, mode: int, path: str) -> None: ...
    def chown(self, owner: int, group: int, path: str) -> None: ...
    def clear_backend_setting(self, name: str) -> int: ...
    def clevis_luks_unlock(self, device: str, mapname: str) -> None: ...
    def command(self, arguments: list[str]) -> str: ...
    def command_lines(self, arguments: list[str]) -> list[str]: ...
    def command_out(self, arguments: list[str], output: str) -> None: ...
    def compress_device_out(self, ctype: str, device: str, zdevice: str, level: int | None = None) -> None: ...
    def compress_out(self, ctype: str, file: str, zfile: str, level: int | None = None) -> None: ...
    def config(self, hvparam: str, hvvalue: str | None) -> None: ...
    def copy_attributes(self, src: str, dest: str, all: bool | None = None, mode: bool | None = None, xattributes: bool | None = None, ownership: bool | None = None) -> None: ...
    def copy_device_to_device(self, src: str, dest: str, srcoffset: int | None = None, destoffset: int | None = None, size: int | None = None, sparse: bool | None = None, append: bool | None = None) -> None: ...
    def copy_device_to_file(self, src: str, dest: str, srcoffset: int | None = None, destoffset: int | None = None, size: int | None = None, sparse: bool | None = None, append: bool | None = None) -> None: ...
    def copy_file_to_device(self, src: str, dest: str, srcoffset: int | None = None, destoffset: int | None = None, size: int | None = None, sparse: bool | None = None, append: bool | None = None) -> None: ...
    def copy_file_to_file(self, src: str, dest: str, srcoffset: int | None = None, destoffset: int | None = None, size: int | None = None, sparse: bool | None = None, append: bool | None = None) -> None: ...
    def copy_in(self, localpath: str, remotedir: str) -> None: ...
    def copy_out(self, remotepath: str, localdir: str) -> None: ...
    def copy_size(self, src: str, dest: str, size: int) -> None: ...
    def cp(self, src: str, dest: str) -> None: ...
    def cp_a(self, src: str, dest: str) -> None: ...
    def cp_r(self, src: str, dest: str) -> None: ...
    def cpio_out(self, directory: str, cpiofile: str, format: str | None = None) -> None: ...
    def cryptsetup_close(self, device: str) -> None: ...
    def cryptsetup_open(self, device: str, key: str, mapname: str, readonly: bool | None = None, crypttype: str | None = None, cipher: str | None = None) -> None: ...
    def dd(self, src: str, dest: str) -> None: ...
    def debug(self, subcmd: str, extraargs: list[str]) -> str: ...
    def debug_drives(self) -> list[str]: ...
    def debug_upload(self, filename: str, tmpname: str, mode: int) -> None: ...
    def device_index(self, device: str) -> int: ...
    def device_name(self, index: int) -> str: ...
    def df(self) -> str: ...
    def df_h(self) -> str: ...
    def disk_create(self, filename: str, format: str, size: int, backingfile: str | None = None, backingformat: str | None = None, preallocation: str | None = None, compat: str | None = None, clustersize: int | None = None) -> None: ...
    def disk_format(self, filename: str) -> str: ...
    def disk_has_backing_file(self, filename: str) -> bool: ...
    def disk_virtual_size(self, filename: str) -> int: ...
    def dmesg(self) -> str: ...
    def download(self, remotefilename: str, filename: str) -> None: ...
    def download_blocks(self, device: str, start: int, stop: int, filename: str, unallocated: bool | None = None) -> None: ...
    def download_inode(self, device: str, inode: int, filename: str) -> None: ...
    def download_offset(self, remotefilename: str, filename: str, offset: int, size: int) -> None: ...
    def drop_caches(self, whattodrop: int) -> None: ...
    def du(self, path: str) -> int: ...
    def e2fsck(self, device: str, correct: bool | None = None, forceall: bool | None = None, forceno: bool | None = None) -> None: ...
    def e2fsck_f(self, device: str) -> None: ...
    def echo_daemon(self, words: list[str]) -> str: ...
    def egrep(self, regex: str, path: str) -> list[str]: ...
    def egrepi(self, regex: str, path: str) -> list[str]: ...
    def equal(self, file1: str, file2: str) -> bool: ...
    def exists(self, path: str) -> bool: ...
    def extlinux(self, directory: str) -> None: ...
    def f2fs_expand(self, device: str) -> None: ...
    def fallocate(self, path: str, len: int) -> None: ...
    def fallocate64(self, path: str, len: int) -> None: ...
    def feature_available(self, groups: list[str]) -> bool: ...
    def fgrep(self, pattern: str, path: str) -> list[str]: ...
    def fgrepi(self, pattern: str, path: str) -> list[str]: ...
    def file(self, path: str) -> str: ...
    def file_architecture(self, filename: str) -> str: ...
    def filesize(self, file: str) -> int: ...
    def filesystem_available(self, filesystem: str) -> bool: ...
    def filesystem_walk(self, device: str) -> list[dict]: ...
    def fill(self, c: int, len: int, path: str) -> None: ...
    def fill_dir(self, dir: str, nr: int) -> None: ...
    def fill_pattern(self, pattern: str, len: int, path: str) -> None: ...
    def find(self, directory: str) -> list[str]: ...
    def find0(self, directory: str, files: str) -> None: ...
    def find_inode(self, device: str, inode: int) -> list[dict]: ...
    def findfs_label(self, label: str) -> str: ...
    def findfs_partlabel(self, label: str) -> str: ...
    def findfs_partuuid(self, uuid: str) -> str: ...
    def findfs_uuid(self, uuid: str) -> str: ...
    def fsck(self, fstype: str, device: str) -> int: ...
    def fstrim(self, mountpoint: str, offset: int | None = None, length: int | None = None, minimumfreeextent: int | None = None) -> None: ...
    def get_append(self) -> str | None: ...
    def get_attach_method(self) -> str: ...
    def get_autosync(self) -> bool: ...
    def get_backend(self) -> str: ...
    def get_backend_setting(self, name: str) -> str: ...
    def get_backend_settings(self) -> list[str]: ...
    def get_cachedir(self) -> str: ...
    def get_direct(self) -> bool: ...
    def get_e2attrs(self, file: str) -> str: ...
    def get_e2generation(self, file: str) -> int: ...
    def get_e2label(self, device: str) -> str: ...
    def get_e2uuid(self, device: str) -> str: ...
    def get_hv(self) -> str: ...
    def get_identifier(self) -> str: ...
    def get_libvirt_requested_credential_challenge(self, index: int) -> str: ...
    def get_libvirt_requested_credential_defresult(self, index: int) -> str: ...
    def get_libvirt_requested_credential_prompt(self, index: int) -> str: ...
    def get_libvirt_requested_credentials(self) -> list[str]: ...
    def get_memsize(self) -> int: ...
    def get_network(self) -> bool: ...
    def get_path(self) -> str: ...
    def get_pgroup(self) -> bool: ...
    def get_pid(self) -> int: ...
    def get_program(self) -> str: ...
    def get_qemu(self) -> str: ...
    def get_recovery_proc(self) -> bool: ...
    def get_selinux(self) -> bool: ...
    def get_smp(self) -> int: ...
    def get_sockdir(self) -> str: ...
    def get_state(self) -> int: ...
    def get_tmpdir(self) -> str: ...
    def get_trace(self) -> bool: ...
    def get_umask(self) -> int: ...
    def get_verbose(self) -> bool: ...
    def getcon(self) -> str: ...
    def getxattr(self, path: str, name: str) -> bytes: ...
    def getxattrs(self, path: str) -> list[dict]: ...
    def glob_expand(self, pattern: str, directoryslash: bool | None = None) -> list[str]: ...
    glob_expand_opts = glob_expand
    def grep(self, regex: str, path: str, extended: bool | None = None, fixed: bool | None = None, insensitive: bool | None = None, compressed: bool | None = None) -> list[str]: ...
    grep_opts = grep
    def grepi(self, regex: str, path: str) -> list[str]: ...
    def grub_install(self, root: str, device: str) -> None: ...
    def head(self, path: str) -> list[str]: ...
    def head_n(self, nrlines: int, path: str) -> list[str]: ...
    def hexdump(self, path: str) -> str: ...
    def hivex_close(self) -> None: ...
    def hivex_commit(self, filename: str | None) -> None: ...
    def hivex_node_add_child(self, parent: int, name: str) -> int: ...
    def hivex_node_children(self, nodeh: int) -> list[dict]: ...
    def hivex_node_delete_child(self, nodeh: int) -> None: ...
    def hivex_node_get_child(self, nodeh: int, name: str) -> int: ...
    def hivex_node_get_value(self, nodeh: int, key: str) -> int: ...
    def hivex_node_name(self, nodeh: int) -> str: ...
    def hivex_node_parent(self, nodeh: int) -> int: ...
    def hivex_node_set_value(self, nodeh: int, key: str, t: int, val: bytes) -> None: ...
    def hivex_node_values(self, nodeh: int) -> list[dict]: ...
    def hivex_open(self, filename: str, verbose: bool | None = None, debug: bool | None = None, write: bool | None = None, unsafe: bool | None = None) -> None: ...
    def hivex_root(self) -> int: ...
    def hivex_value_key(self, valueh: int) -> str: ...
    def hivex_value_string(self, valueh: int) -> str: ...
    def hivex_value_type(self, valueh: int) -> int: ...
    def hivex_value_utf8(self, valueh: int) -> str: ...
    def hivex_value_value(self, valueh: int) -> bytes: ...
    def initrd_cat(self, initrdpath: str, filename: str) -> bytes: ...
    def initrd_list(self, path: str) -> list[str]: ...
    def inotify_add_watch(self, path: str, mask: int) -> int: ...
    def inotify_close(self) -> None: ...
    def inotify_files(self) -> list[str]: ...
    def inotify_init(self, maxevents: int) -> None: ...
    def inotify_read(self) -> list[dict]: ...
    def inotify_rm_watch(self, wd: int) -> None: ...
    def inspect_get_arch(self, root: str) -> str: ...
    def inspect_get_build_id(self, root: str) -> str: ...
    def inspect_get_distro(self, root: str) -> str: ...
    def inspect_get_drive_mappings(self, root: str) -> list[tuple[str, str]] | dict: ...
    def inspect_get_filesystems(self, root: str) -> list[str]: ...
    def inspect_get_format(self, root: str) -> str: ...
    def inspect_get_hostname(self, root: str) -> str: ...
    def inspect_get_icon(self, root: str, favicon: bool | None = None, highquality: bool | None = None) -> bytes: ...
    def inspect_get_major_version(self, root: str) -> int: ...
    def inspect_get_minor_version(self, root: str) -> int: ...
    def inspect_get_mountpoints(self, root: str) -> list[tuple[str, str]] | dict: ...
    def inspect_get_osinfo(self, root: str) -> str: ...
    def inspect_get_package_format(self, root: str) -> str: ...
    def inspect_get_package_management(self, root: str) -> str: ...
    def inspect_get_product_name(self, root: str) -> str: ...
    def inspect_get_product_variant(self, root: str) -> str: ...
    def inspect_get_roots(self) -> list[str]: ...
    def inspect_get_type(self, root: str) -> str: ...
    def inspect_get_windows_current_control_set(self, root: str) -> str: ...
    def inspect_get_windows_software_hive(self, root: str) -> str: ...
    def inspect_get_windows_system_hive(self, root: str) -> str: ...
    def inspect_get_windows_systemroot(self, root: str) -> str: ...
    def inspect_is_live(self, root: str) -> bool: ...
    def inspect_is_multipart(self, root: str) -> bool: ...
    def inspect_is_netinst(self, root: str) -> bool: ...
    def inspect_list_applications(self, root: str) -> list[dict]: ...
    def inspect_list_applications2(self, root: str) -> list[dict]: ...
    def inspect_os(self) -> list[str]: ...
    def internal_exit(self) -> None: ...
    def internal_test(self, str: str, optstr: str | None, strlist: list[str], b: bool, integer: int, integer64: int, filein: str, fileout: str, bufferin: bytes, obool: bool | None = None, oint: int | None = None, oint64: int | None = None, ostring: str | None = None, ostringlist: list[str] | None = None) -> None: ...
    def internal_test_63_optargs(self, opt1: int | None = None, opt2: int | None = None, opt3: int | None = None, opt4: int | None = None, opt5: int | None = None, opt6: int | None = None, opt7: int | None = None, opt8: int | None = None, opt9: int | None = None, opt10: int | None = None, opt11: int | None = None, opt12: int | None = None, opt13: int | None = None, opt14: int | None = None, opt15: int | None = None, opt16: int | None = None, opt17: int | None = None, opt18: int | None = None, opt19: int | None = None, opt20: int | None = None, opt21: int | None = None, opt22: int | None = None, opt23: int | None = None, opt24: int | None = None, opt25: int | None = None, opt26: int | None = None, opt27: int | None = None, opt28: int | None = None, opt29: int | None = None, opt30: int | None = None, opt31: int | None = None, opt32: int | None = None, opt33: int | None = None, opt34: int | None = None, opt35: int | None = None, opt36: int | None = None, opt37: int | None = None, opt38: int | None = None, opt39: int | None = None, opt40: int | None = None, opt41: int | None = None, opt42: int | None = None, opt43: int | None = None, opt44: int | None = None, opt45: int | None = None, opt46: int | None = None, opt47: int | None = None, opt48: int | None = None, opt49: int | None = None, opt50: int | None = None, opt51: int | None = None, opt52: int | None = None, opt53: int | None = None, opt54: int | None = None, opt55: int | None = None, opt56: int | None = None, opt57: int | None = None, opt58: int | None = None, opt59: int | None = None, opt60: int | None = None, opt61: int | None = None, opt62: int | None = None, opt63: int | None = None) -> None: ...
    def internal_test_close_output(self) -> None: ...
    def internal_test_only_optargs(self, test: int | None = None) -> None: ...
    def internal_test_rbool(self, val: str) -> bool: ...
    def internal_test_rboolerr(self) -> bool: ...
    def internal_test_rbufferout(self, val: str) -> bytes: ...
    def internal_test_rbufferouterr(self) -> bytes: ...
    def internal_test_rconstoptstring(self, val: str) -> str | None: ...
    def internal_test_rconstoptstringerr(self) -> str | None: ...
    def internal_test_rconststring(self, val: str) -> str: ...
    def internal_test_rconststringerr(self) -> str: ...
    def internal_test_rhashtable(self, val: str) -> list[tuple[str, str]] | dict: ...
    def internal_test_rhashtableerr(self) -> list[tuple[str, str]] | dict: ...
    def internal_test_rint(self, val: str) -> int: ...
    def internal_test_rint64(self, val: str) -> int: ...
    def internal_test_rint64err(self) -> int: ...
    def internal_test_rinterr(self) -> int: ...
    def internal_test_rstring(self, val: str) -> str: ...
    def internal_test_rstringerr(self) -> str: ...
    def internal_test_rstringlist(self, val: str) -> list[str]: ...
    def internal_test_rstringlisterr(self) -> list[str]: ...
    def internal_test_rstruct(self, val: str) -> dict: ...
    def internal_test_rstructerr(self) -> dict: ...
    def internal_test_rstructlist(self, val: str) -> list[dict]: ...
    def internal_test_rstructlisterr(self) -> list[dict]: ...
    def internal_test_set_output(self, filename: str) -> None: ...
    def is_blockdev(self, path: str, followsymlinks: bool | None = None) -> bool: ...
    is_blockdev_opts = is_blockdev
    def is_busy(self) -> bool: ...
    def is_chardev(self, path: str, followsymlinks: bool | None = None) -> bool: ...
    is_chardev_opts = is_chardev
    def is_config(self) -> bool: ...
    def is_dir(self, path: str, followsymlinks: bool | None = None) -> bool: ...
    is_dir_opts = is_dir
    def is_fifo(self, path: str, followsymlinks: bool | None = None) -> bool: ...
    is_fifo_opts = is_fifo
    def is_file(self, path: str, followsymlinks: bool | None = None) -> bool: ...
    is_file_opts = is_file
    def is_launching(self) -> bool: ...
    def is_lv(self, mountable: str) -> bool: ...
    def is_ready(self) -> bool: ...
    def is_socket(self, path: str, followsymlinks: bool | None = None) -> bool: ...
    is_socket_opts = is_socket
    def is_symlink(self, path: str) -> bool: ...
    def is_whole_device(self, device: str) -> bool: ...
    def is_zero(self, path: str) -> bool: ...
    def is_zero_device(self, device: str) -> bool: ...
    def isoinfo(self, isofile: str) -> dict: ...
    def isoinfo_device(self, device: str) -> dict: ...
    def journal_close(self) -> None: ...
    def journal_get(self) -> list[dict]: ...
    def journal_get_data_threshold(self) -> int: ...
    def journal_get_realtime_usec(self) -> int: ...
    def journal_next(self) -> bool: ...
    def journal_open(self, directory: str) -> None: ...
    def journal_set_data_threshold(self, threshold: int) -> None: ...
    def journal_skip(self, skip: int) -> int: ...
    def kill_subprocess(self) -> None: ...
    def launch(self) -> None: ...
    def lchown(self, owner: int, group: int, path: str) -> None: ...
    def ldmtool_create_all(self) -> None: ...
    def ldmtool_diskgroup_disks(self, diskgroup: str) -> list[str]: ...
    def ldmtool_diskgroup_name(self, diskgroup: str) -> str: ...
    def ldmtool_diskgroup_volumes(self, diskgroup: str) -> list[str]: ...
    def ldmtool_remove_all(self) -> None: ...
    def ldmtool_scan(self) -> list[str]: ...
    def ldmtool_scan_devices(self, devices: list[str]) -> list[str]: ...
    def ldmtool_volume_hint(self, diskgroup: str, volume: str) -> str: ...
    def ldmtool_volume_partitions(self, diskgroup: str, volume: str) -> list[str]: ...
    def ldmtool_volume_type(self, diskgroup: str, volume: str) -> str: ...
    def lgetxattr(self, path: str, name: str) -> bytes: ...
    def lgetxattrs(self, path: str) -> list[dict]: ...
    def list_9p(self) -> list[str]: ...
    def list_devices(self) -> list[str]: ...
    def list_disk_labels(self) -> list[tuple[str, str]] | dict: ...
    def list_dm_devices(self) -> list[str]: ...
    def list_filesystems(self) -> list[tuple[str, str]] | dict: ...
    def list_ldm_partitions(self) -> list[str]: ...
    def list_ldm_volumes(self) -> list[str]: ...
    def list_md_devices(self) -> list[str]: ...
    def list_partitions(self) -> list[str]: ...
    def ll(self, directory: str) -> str: ...
    def llz(self, directory: str) -> str: ...
    def ln(self, target: str, linkname: str) -> None: ...
    def ln_f(self, target: str, linkname: str) -> None: ...
    def ln_s(self, target: str, linkname: str) -> None: ...
    def ln_sf(self, target: str, linkname: str) -> None: ...
    def lremovexattr(self, xattr: str, path: str) -> None: ...
    def ls(self, directory: str) -> list[str]: ...
    def ls0(self, dir: str, filenames: str) -> None: ...
    def lsetxattr(self, xattr: str, val: str, vallen: int, path: str) -> None: ...
    def lstat(self, path: str) -> dict: ...
    def lstatlist(self, path: str, names: list[str]) -> list[dict]: ...
    def lstatns(self, path: str) -> dict: ...
    def lstatnslist(self, path: str, names: list[str]) -> list[dict]: ...
    def luks_add_key(self, device: str, key: str, newkey: str, keyslot: int) -> None: ...
    def luks_close(self, device: str) -> None: ...
    def luks_format(self, device: str, key: str, keyslot: int) -> None: ...
    def luks_format_cipher(self, device: str, key: str, keyslot: int, cipher: str) -> None: ...
    def luks_kill_slot(self, device: str, key: str, keyslot: int) -> None: ...
    def luks_open(self, device: str, key: str, mapname: str) -> None: ...
    def luks_open_ro(self, device: str, key: str, mapname: str) -> None: ...
    def luks_uuid(self, device: str) -> str: ...
    def lvcreate(self, logvol: str, volgroup: str, mbytes: int) -> None: ...
    def lvcreate_free(self, logvol: str, volgroup: str, percent: int) -> None: ...
    def lvm_canonical_lv_name(self, lvname: str) -> str: ...
    def lvm_clear_filter(self) -> None: ...
    def lvm_remove_all(self) -> None: ...
    def lvm_scan(self, activate: bool) -> None: ...
    def lvm_set_filter(self, devices: list[str]) -> None: ...
    def lvremove(self, device: str) -> None: ...
    def lvrename(self, logvol: str, newlogvol: str) -> None: ...
    def lvresize(self, device: str, mbytes: int) -> None: ...
    def lvresize_free(self, lv: str, percent: int) -> None: ...
    def lvs(self) -> list[str]: ...
    def lvs_full(self) -> list[dict]: ...
    def lvuuid(self, device: str) -> str: ...
    def lxattrlist(self, path: str, names: list[str]) -> list[dict]: ...
    def max_disks(self) -> int: ...
    def md_create(self, name: str, devices: list[str], missingbitmap: int | None = None, nrdevices: int | None = None, spare: int | None = None, chunk: int | None = None, level: str | None = None) -> None: ...
    def md_detail(self, md: str) -> list[tuple[str, str]] | dict: ...
    def md_stat(self, md: str) -> list[dict]: ...
    def md_stop(self, md: str) -> None: ...
    def mkdir(self, path: str) -> None: ...
    def mkdir_mode(self, path: str, mode: int) -> None: ...
    def mkdir_p(self, path: str) -> None: ...
    def mkdtemp(self, tmpl: str) -> str: ...
    def mke2fs(self, device: str, blockscount: int | None = None, blocksize: int | None = None, fragsize: int | None = None, blockspergroup: int | None = None, numberofgroups: int | None = None, bytesperinode: int | None = None, inodesize: int | None = None, journalsize: int | None = None, numberofinodes: int | None = None, stridesize: int | None = None, stripewidth: int | None = None, maxonlineresize: int | None = None, reservedblockspercentage: int | None = None, mmpupdateinterval: int | None = None, journaldevice: str | None = None, label: str | None = None, lastmounteddir: str | None = None, creatoros: str | None = None, fstype: str | None = None, usagetype: str | None = None, uuid: str | None = None, forcecreate: bool | None = None, writesbandgrouponly: bool | None = None, lazyitableinit: bool | None = None, lazyjournalinit: bool | None = None, testfs: bool | None = None, discard: bool | None = None, quotatype: bool | None = None, extent: bool | None = None, filetype: bool | None = None, flexbg: bool | None = None, hasjournal: bool | None = None, journaldev: bool | None = None, largefile: bool | None = None, quota: bool | None = None, resizeinode: bool | None = None, sparsesuper: bool | None = None, uninitbg: bool | None = None) -> None: ...
    def mke2fs_J(self, fstype: str, blocksize: int, device: str, journal: str) -> None: ...
    def mke2fs_JL(self, fstype: str, blocksize: int, device: str, label: str) -> None: ...
    def mke2fs_JU(self, fstype: str, blocksize: int, device: str, uuid: str) -> None: ...
    def mke2journal(self, blocksize: int, device: str) -> None: ...
    def mke2journal_L(self, blocksize: int, label: str, device: str) -> None: ...
    def mke2journal_U(self, blocksize: int, uuid: str, device: str) -> None: ...
    def mkfifo(self, mode: int, path: str) -> None: ...
    def mkfs(self, fstype: str, device: str, blocksize: int | None = None, features: str | None = None, inode: int | None = None, sectorsize: int | None = None, label: str | None = None) -> None: ...
    mkfs_opts = mkfs
    def mkfs_b(self, fstype: str, blocksize: int, device: str) -> None: ...
    def mkfs_btrfs(self, devices: list[str], allocstart: int | None = None, bytecount: int | None = None, datatype: str | None = None, leafsize: int | None = None, label: str | None = None, metadata: str | None = None, nodesize: int | None = None, sectorsize: int | None = None) -> None: ...
    def mklost_and_found(self, mountpoint: str) -> None: ...
    def mkmountpoint(self, exemptpath: str) -> None: ...
    def mknod(self, mode: int, devmajor: int, devminor: int, path: str) -> None: ...
    def mknod_b(self, mode: int, devmajor: int, devminor: int, path: str) -> None: ...
    def mknod_c(self, mode: int, devmajor: int, devminor: int, path: str) -> None: ...
    def mksquashfs(self, path: str, filename: str, compress: str | None = None, excludes: list[str] | None = None) -> None: ...
    def mkswap(self, device: str, label: str | None = None, uuid: str | None = None) -> None: ...
    mkswap_opts = mkswap
    def mkswap_L(self, label: str, device: str) -> None: ...
    def mkswap_U(self, uuid: str, device: str) -> None: ...
    def mkswap_file(self, path: str) -> None: ...
    def mktemp(self, tmpl: str, suffix: str | None = None) -> str: ...
    def modprobe(self, modulename: str) -> None: ...
    def mount(self, mountable: str, mountpoint: str) -> None: ...
    def mount_9p(self, mounttag: str, mountpoint: str, options: str | None = None) -> None: ...
    def mount_local(self, localmountpoint: str, readonly: bool | None = None, options: str | None = None, cachetimeout: int | None = None, debugcalls: bool | None = None) -> None: ...
    def mount_local_run(self) -> None: ...
    def mount_loop(self, file: str, mountpoint: str) -> None: ...
    def mount_options(self, options: str, mountable: str, mountpoint: str) -> None: ...
    def mount_ro(self, mountable: str, mountpoint: str) -> None: ...
    def mount_vfs(self, options: str, vfstype: str, mountable: str, mountpoint: str) -> None: ...
    def mountable_device(self, mountable: str) -> str: ...
    def mountable_subvolume(self, mountable: str) -> str: ...
    def mountpoints(self) -> list[tuple[str, str]] | dict: ...
    def mounts(self) -> list[str]: ...
    def mv(self, src: str, dest: str) -> None: ...
    def nr_devices(self) -> int: ...
    def ntfs_3g_probe(self, rw: bool, device: str) -> int: ...
    def ntfscat_i(self, device: str, inode: int, filename: str) -> None: ...
    def ntfsclone_in(self, backupfile: str, device: str) -> None: ...
    def ntfsclone_out(self, device: str, backupfile: str, metadataonly: bool | None = None, rescue: bool | None = None, ignorefscheck: bool | None = None, preservetimestamps: bool | None = None, force: bool | None = None) -> None: ...
    def ntfsfix(self, device: str, clearbadsectors: bool | None = None) -> None: ...
    def ntfsresize(self, device: str, size: int | None = None, force: bool | None = None) -> None: ...
    ntfsresize_opts = ntfsresize
    def ntfsresize_size(self, device: str, size: int) -> None: ...
    def parse_environment(self) -> None: ...
    def parse_environment_list(self, environment: list[str]) -> None: ...
    def part_add(self, device: str, prlogex: str, startsect: int, endsect: int) -> None: ...
    def part_del(self, device: str, partnum: int) -> None: ...
    def part_disk(self, device: str, parttype: str) -> None: ...
    def part_expand_gpt(self, device: str) -> None: ...
    def part_get_bootable(self, device: str, partnum: int) -> bool: ...
    def part_get_disk_guid(self, device: str) -> str: ...
    def part_get_gpt_attributes(self, device: str, partnum: int) -> int: ...
    def part_get_gpt_guid(self, device: str, partnum: int) -> str: ...
    def part_get_gpt_type(self, device: str, partnum: int) -> str: ...
    def part_get_mbr_id(self, device: str, partnum: int) -> int: ...
    def part_get_mbr_part_type(self, device: str, partnum: int) -> str: ...
    def part_get_name(self, device: str, partnum: int) -> str: ...
    def part_get_parttype(self, device: str) -> str: ...
    def part_init(self, device: str, parttype: str) -> None: ...
    def part_list(self, device: str) -> list[dict]: ...
    def part_resize(self, device: str, partnum: int, endsect: int) -> None: ...
    def part_set_bootable(self, device: str, partnum: int, bootable: bool) -> None: ...
    def part_set_disk_guid(self, device: str, guid: str) -> None: ...
    def part_set_disk_guid_random(self, device: str) -> None: ...
    def part_set_gpt_attributes(self, device: str, partnum: int, attributes: int) -> None: ...
    def part_set_gpt_guid(self, device: str, partnum: int, guid: str) -> None: ...
    def part_set_gpt_type(self, device: str, partnum: int, guid: str) -> None: ...
    def part_set_mbr_id(self, device: str, partnum: int, idbyte: int) -> None: ...
    def part_set_name(self, device: str, partnum: int, name: str) -> None: ...
    def part_to_dev(self, partition: str) -> str: ...
    def part_to_partnum(self, partition: str) -> int: ...
    def ping_daemon(self) -> None: ...
    def pread(self, path: str, count: int, offset: int) -> bytes: ...
    def pread_device(self, device: str, count: int, offset: int) -> bytes: ...
    def pvchange_uuid(self, device: str) -> None: ...
    def pvchange_uuid_all(self) -> None: ...
    def pvcreate(self, device: str) -> None: ...
    def pvremove(self, device: str) -> None: ...
    def pvresize(self, device: str) -> None: ...
    def pvresize_size(self, device: str, size: int) -> None: ...
    def pvs(self) -> list[str]: ...
    def pvs_full(self) -> list[dict]: ...
    def pvuuid(self, device: str) -> str: ...
    def pwrite(self, path: str, content: bytes, offset: int) -> int: ...
    def pwrite_device(self, device: str, content: bytes, offset: int) -> int: ...
    def read_file(self, path: str) -> bytes: ...
    def read_lines(self, path: str) -> list[str]: ...
    def readdir(self, dir: str) -> list[dict]: ...
    def readlink(self, path: str) -> str: ...
    def readlinklist(self, path: str, names: list[str]) -> list[str]: ...
    def realpath(self, path: str) -> str: ...
    def remount(self, mountpoint: str, rw: bool | None = None) -> None: ...
    def remove_drive(self, label: str) -> None: ...
    def removexattr(self, xattr: str, path: str) -> None: ...
    def rename(self, oldpath: str, newpath: str) -> None: ...
    def resize2fs(self, device: str) -> None: ...
    def resize2fs_M(self, device: str) -> None: ...
    def resize2fs_size(self, device: str, size: int) -> None: ...
    def rm(self, path: str) -> None: ...
    def rm_f(self, path: str) -> None: ...
    def rm_rf(self, path: str) -> None: ...
    def rmdir(self, path: str) -> None: ...
    def rmmountpoint(self, exemptpath: str) -> None: ...
    def rsync(self, src: str, dest: str, archive: bool | None = None, deletedest: bool | None = None) -> None: ...
    def rsync_in(self, remote: str, dest: str, archive: bool | None = None, deletedest: bool | None = None) -> None: ...
    def rsync_out(self, src: str, remote: str, archive: bool | None = None, deletedest: bool | None = None) -> None: ...
    def scrub_device(self, device: str) -> None: ...
    def scrub_file(self, file: str) -> None: ...
    def scrub_freespace(self, dir: str) -> None: ...
    def selinux_relabel(self, specfile: str, path: str, force: bool | None = None) -> None: ...
    def set_append(self, append: str | None) -> None: ...
    def set_attach_method(self, backend: str) -> None: ...
    def set_autosync(self, autosync: bool) -> None: ...
    def set_backend(self, backend: str) -> None: ...
    def set_backend_setting(self, name: str, val: str) -> None: ...
    def set_backend_settings(self, settings: list[str]) -> None: ...
    def set_cachedir(self, cachedir: str | None) -> None: ...
    def set_direct(self, direct: bool) -> None: ...
    def set_e2attrs(self, file: str, attrs: str, clear: bool | None = None) -> None: ...
    def set_e2generation(self, file: str, generation: int) -> None: ...
    def set_e2label(self, device: str, label: str) -> None: ...
    def set_e2uuid(self, device: str, uuid: str) -> None: ...
    def set_hv(self, hv: str) -> None: ...
    def set_identifier(self, identifier: str) -> None: ...
    def set_label(self, mountable: str, label: str) -> None: ...
    def set_libvirt_requested_credential(self, index: int, cred: bytes) -> None: ...
    def set_libvirt_supported_credentials(self, creds: list[str]) -> None: ...
    def set_memsize(self, memsize: int) -> None: ...
    def set_network(self, network: bool) -> None: ...
    def set_path(self, searchpath: str | None) -> None: ...
    def set_pgroup(self, pgroup: bool) -> None: ...
    def set_program(self, program: str) -> None: ...
    def set_qemu(self, hv: str | None) -> None: ...
    def set_recovery_proc(self, recoveryproc: bool) -> None: ...
    def set_selinux(self, selinux: bool) -> None: ...
    def set_smp(self, smp: int) -> None: ...
    def set_tmpdir(self, tmpdir: str | None) -> None: ...
    def set_trace(self, trace: bool) -> None: ...
    def set_uuid(self, device: str, uuid: str) -> None: ...
    def set_uuid_random(self, device: str) -> None: ...
    def set_verbose(self, verbose: bool) -> None: ...
    def setcon(self, context: str) -> None: ...
    def setxattr(self, xattr: str, val: str, vallen: int, path: str) -> None: ...
    def sfdisk(self, device: str, cyls: int, heads: int, sectors: int, lines: list[str]) -> None: ...
    def sfdiskM(self, device: str, lines: list[str]) -> None: ...
    def sfdisk_N(self, device: str, partnum: int, cyls: int, heads: int, sectors: int, line: str) -> None: ...
    def sfdisk_disk_geometry(self, device: str) -> str: ...
    def sfdisk_kernel_geometry(self, device: str) -> str: ...
    def sfdisk_l(self, device: str) -> str: ...
    def sh(self, command: str) -> str: ...
    def sh_lines(self, command: str) -> list[str]: ...
    def sh_out(self, command: str, output: str) -> None: ...
    def shutdown(self) -> None: ...
    def sleep(self, secs: int) -> None: ...
    def stat(self, path: str) -> dict: ...
    def statns(self, path: str) -> dict: ...
    def statvfs(self, path: str) -> dict: ...
    def strings(self, path: str) -> list[str]: ...
    def strings_e(self, encoding: str, path: str) -> list[str]: ...
    def swapoff_device(self, device: str) -> None: ...
    def swapoff_file(self, file: str) -> None: ...
    def swapoff_label(self, label: str) -> None: ...
    def swapoff_uuid(self, uuid: str) -> None: ...
    def swapon_device(self, device: str) -> None: ...
    def swapon_file(self, file: str) -> None: ...
    def swapon_label(self, label: str) -> None: ...
    def swapon_uuid(self, uuid: str) -> None: ...
    def sync(self) -> None: ...
    def syslinux(self, device: str, directory: str | None = None) -> None: ...
    def tail(self, path: str) -> list[str]: ...
    def tail_n(self, nrlines: int, path: str) -> list[str]: ...
    def tar_in(self, tarfile: str, directory: str, compress: str | None = None, xattrs: bool | None = None, selinux: bool | None = None, acls: bool | None = None) -> None: ...
    tar_in_opts = tar_in
    def tar_out(self, directory: str, tarfile: str, compress: str | None = None, numericowner: bool | None = None, excludes: list[str] | None = None, xattrs: bool | None = None, selinux: bool | None = None, acls: bool | None = None) -> None: ...
    tar_out_opts = tar_out
    def tgz_in(self, tarball: str, directory: str) -> None: ...
    def tgz_out(self, directory: str, tarball: str) -> None: ...
    def touch(self, path: str) -> None: ...
    def truncate(self, path: str) -> None: ...
    def truncate_size(self, path: str, size: int) -> None: ...
    def tune2fs(self, device: str, force: bool | None = None, maxmountcount: int | None = None, mountcount: int | None = None, errorbehavior: str | None = None, group: int | None = None, intervalbetweenchecks: int | None = None, reservedblockspercentage: int | None = None, lastmounteddirectory: str | None = None, reservedblockscount: int | None = None, user: int | None = None) -> None: ...
    def tune2fs_l(self, device: str) -> list[tuple[str, str]] | dict: ...
    def txz_in(self, tarball: str, directory: str) -> None: ...
    def txz_out(self, directory: str, tarball: str) -> None: ...
    def umask(self, mask: int) -> int: ...
    def umount(self, pathordevice: str, force: bool | None = None, lazyunmount: bool | None = None) -> None: ...
    umount_opts = umount
    def umount_all(self) -> None: ...
    def umount_local(self, retry: bool | None = None) -> None: ...
    def upload(self, filename: str, remotefilename: str) -> None: ...
    def upload_offset(self, filename: str, remotefilename: str, offset: int) -> None: ...
    def user_cancel(self) -> None: ...
    def utimens(self, path: str, atsecs: int, atnsecs: int, mtsecs: int, mtnsecs: int) -> None: ...
    def utsname(self) -> dict: ...
    def version(self) -> dict: ...
    def vfs_label(self, mountable: str) -> str: ...
    def vfs_minimum_size(self, mountable: str) -> int: ...
    def vfs_type(self, mountable: str) -> str: ...
    def vfs_uuid(self, mountable: str) -> str: ...
    def vg_activate(self, activate: bool, volgroups: list[str]) -> None: ...
    def vg_activate_all(self, activate: bool) -> None: ...
    def vgchange_uuid(self, vg: str) -> None: ...
    def vgchange_uuid_all(self) -> None: ...
    def vgcreate(self, volgroup: str, physvols: list[str]) -> None: ...
    def vglvuuids(self, vgname: str) -> list[str]: ...
    def vgmeta(self, vgname: str) -> bytes: ...
    def vgpvuuids(self, vgname: str) -> list[str]: ...
    def vgremove(self, vgname: str) -> None: ...
    def vgrename(self, volgroup: str, newvolgroup: str) -> None: ...
    def vgs(self) -> list[str]: ...
    def vgs_full(self) -> list[dict]: ...
    def vgscan(self) -> None: ...
    def vguuid(self, vgname: str) -> str: ...
    def wait_ready(self) -> None: ...
    def wc_c(self, path: str) -> int: ...
    def wc_l(self, path: str) -> int: ...
    def wc_w(self, path: str) -> int: ...
    def wipefs(self, device: str) -> None: ...
    def write(self, path: str, content: bytes) -> None: ...
    def write_append(self, path: str, content: bytes) -> None: ...
    def write_file(self, path: str, content: str, size: int) -> None: ...
    def xfs_admin(self, device: str, extunwritten: bool | None = None, imgfile: bool | None = None, v2log: bool | None = None, projid32bit: bool | None = None, lazycounter: bool | None = None, label: str | None = None, uuid: str | None = None) -> None: ...
    def xfs_growfs(self, path: str, datasec: bool | None = None, logsec: bool | None = None, rtsec: bool | None = None, datasize: int | None = None, logsize: int | None = None, rtsize: int | None = None, rtextsize: int | None = None, maxpct: int | None = None) -> None: ...
    def xfs_info(self, pathordevice: str) -> dict: ...
    def xfs_repair(self, device: str, forcelogzero: bool | None = None, nomodify: bool | None = None, noprefetch: bool | None = None, forcegeometry: bool | None = None, maxmem: int | None = None, ihashsize: int | None = None, bhashsize: int | None = None, agstride: int | None = None, logdev: str | None = None, rtdev: str | None = None) -> int: ...
    def yara_destroy(self) -> None: ...
    def yara_load(self, filename: str) -> None: ...
    def yara_scan(self, path: str) -> list[dict]: ...
    def zegrep(self, regex: str, path: str) -> list[str]: ...
    def zegrepi(self, regex: str, path: str) -> list[str]: ...
    def zero(self, device: str) -> None: ...
    def zero_device(self, device: str) -> None: ...
    def zero_free_space(self, directory: str) -> None: ...
    def zerofree(self, device: str) -> None: ...
    def zfgrep(self, pattern: str, path: str) -> list[str]: ...
    def zfgrepi(self, pattern: str, path: str) -> list[str]: ...
    def zfile(self, meth: str, path: str) -> str: ...
    def zgrep(self, regex: str, path: str) -> list[str]: ...
    def zgrepi(self, regex: str, path: str) -> list[str]: ...
